### ISSUE TITLE
Add more emojis to the README

### ISSUE THREAD

**Issue by Lunarelements** [Lunarelements/low-poly#12]
Every good README could use some extra emoji flair! I would love to see some added to it 😄

**Comment by lucalves** [comment]
Hello @Lunarelements, how are you? Congratulations for this project.

I've added some emojis, feel free to change if you don't approve of any of them.

😁

**Comment by Lunarelements** [comment]
Hey there @lucalves, I appreciate the help! Hope your holidays are going well!
