### ISSUE TITLE
Clear Canvases on New File Upload

### ISSUE THREAD

**Issue by Lunarelements** [Lunarelements/low-poly#15]
If you upload one image, do your thing and then upload another, the new image will be placed over top the old one. This makes you have to manually remove some of the funky background. It would be nice if everything cleared itself after a new upload.

**Comment by malviya-abhishek** [comment]
Hi, can I work on this issue?

**Comment by Lunarelements** [comment]
The one you submitted did the trick @malviya-abhishek. Thanks for the help all!
